### ISSUE TITLE
re: patches for online matlib

### ISSUE THREAD

**Issue by meta-androcto** [sambler/myblendercontrib#4]
hi I noticed finally your patches here: https://developer.blender.org/T37908
would you have any current working patched version, or could you apply your patches & send me the working __init__ . groups is still broken in the latest version & I would really like to fix in contrib.
thanks.
Brendon.

**Comment by meta-androcto** [comment]
hi again, I'm really hoping you can help fix the online matlib issue, you have done lot's of work on it already. It's the best system I've found but without groups, not really that useful & may need to be removed from blender. I'm not that great with patches, even if you could send me a working old version, .py not patch, maybe & can work forward from there.
Thanks.
Brendon.

**Comment by sambler** [comment]
Hi sorry for the delay, I actually didn't notice your first post.

I have just submitted an update for the online_mat_lib to get it working again, including support for newer nodes, https://developer.blender.org/T37908#350955

If you want to skip the patch you can get the full file [here](https://github.com/sambler/myblendercontrib/blob/master/online_mat_lib/__init__.py) I also updated one of the bundled materials - [pool_tiles](https://github.com/sambler/myblendercontrib/blob/master/online_mat_lib/material-library/bundled/cycles/stones/pool_tiles.bcm)

**Comment by meta-androcto** [comment]
hi, thank you very much, I do prefer files to patches, I know you have invested much time in this addon with your osl files & library. I wonder if we could move the online part to github address. Any ideas on this?
Thanks again, update seems to work fine, just a few more tests to do.
